[general]
interval=1

[defaults]
context=from-dongle-custom
rxgain=0
txgain=0
autodeletesms=yes
resetdongle=yes
u2diag=-1
usecallingpres=yes
callingpres=allowed_passed_screen
disablesms=no
language=en
smsaspdu=yes
callwaiting=disable
disable=no
initstate=start
dtmf=relax

[dongle0]
audio=/dev/ttyUSB1
data=/dev/ttyUSB2

[dongle1]
audio=/dev/ttyUSB4
data=/dev/ttyUSB5

[dongle2]
audio=/dev/ttyUSB7
data=/dev/ttyUSB8

[dongle3]
audio=/dev/ttyUSB10
data=/dev/ttyUSB11

[dongle4]
audio=/dev/ttyUSB13
data=/dev/ttyUSB14

[dongle5]
audio=/dev/ttyUSB16
data=/dev/ttyUSB17

[dongle6]
audio=/dev/ttyUSB19
data=/dev/ttyUSB20

[dongle7]
audio=/dev/ttyUSB22
data=/dev/ttyUSB23

[dongle8]
audio=/dev/ttyUSB25
data=/dev/ttyUSB26

[dongle9]
audio=/dev/ttyUSB28
data=/dev/ttyUSB29
